const $ = id => document.getElementById(id);
const $$ = sel => [...document.querySelectorAll(sel)];
const KEYS = { cases:'cc_v14_cases', audits:'cc_v14_audits', notifications:'cc_v14_notifications', results:'cc_v14_results', xp:'cc_v14_xp' };
const CASE_PASS = 'casos2026';
const MANAGER_PASS = 'gestor2026';
let selectedMode = 'plantao', activeCase = null, currentSession = null, timer = null;
let conversationTurns = 0;
function uid(prefix='id'){ return `${prefix}_${Date.now()}_${Math.random().toString(16).slice(2)}`; }
function load(key, fallback=[]){ try{return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback));}catch{return fallback;} }
function save(key, value){ localStorage.setItem(key, JSON.stringify(value)); }
function getCases(){ const stored=load(KEYS.cases,null); if(stored) return stored; save(KEYS.cases, window.CONCREDITO_DEFAULT_CASES); return window.CONCREDITO_DEFAULT_CASES; }
function setCases(cases){ save(KEYS.cases,cases); refreshAll(); }
function audit(action, title){ const items=load(KEYS.audits); items.unshift({id:uid('audit'), action, title, by:'Equipe', at:new Date().toISOString()}); save(KEYS.audits,items); }
function notify(title,message){ const items=load(KEYS.notifications); items.unshift({id:uid('not'), title, message, at:new Date().toISOString(), read:false}); save(KEYS.notifications,items); refreshNotifications(); }
function show(id){ $$('.screen').forEach(s=>s.classList.remove('active')); $(id).classList.add('active'); window.scrollTo(0,0); }
function productOptions(includeAll=false){ return `${includeAll?'<option value="todos">Todos os produtos</option>':''}${window.CONCREDITO_PRODUCTS.map(p=>`<option>${p}</option>`).join('')}`; }
function fillSelects(){ ['productFilter','libraryProduct','caseProduct','casePanelProduct'].forEach(id=>$(id).innerHTML=productOptions(id!=='caseProduct')); $('caseCategory').innerHTML=window.CONCREDITO_CATEGORIES.map(x=>`<option>${x}</option>`).join(''); $('caseProfile').innerHTML=window.CONCREDITO_PROFILES.map(x=>`<option>${x}</option>`).join(''); }
function activeCases(){ return getCases().filter(c=>c.status!=='inativo'); }
function filteredCases(mode=selectedMode){ const prod=$('productFilter').value, diff=$('difficultyFilter').value; return activeCases().filter(c=>(!c.modes||c.modes.includes(mode)) && (prod==='todos'||!prod||c.product===prod) && (diff==='todos'||c.difficulty===diff)); }
function caseCard(c, actions=false){ return `<div class="caseCard" data-id="${c.id}"><b>${c.title}</b><small>${c.product} • ${c.category} • ${c.difficulty} • ${c.profile}</small><p>${c.message}</p><div class="tags">${(c.tags||[]).slice(0,5).map(t=>`<span>${t}</span>`).join('')}<span>${c.status||'ativo'}</span></div>${actions?`<div class="actions"><button class="secondary small editCase" data-id="${c.id}">Editar</button><button class="secondary small dupCase" data-id="${c.id}">Duplicar</button><button class="secondary small toggleCase" data-id="${c.id}">${c.status==='inativo'?'Ativar':'Inativar'}</button><button class="secondary small delCase" data-id="${c.id}">Excluir</button></div>`:''}</div>`; }
function refreshHome(){ const results=load(KEYS.results); const xp=Number(localStorage.getItem(KEYS.xp)||0); const avg=results.length?Math.round(results.reduce((s,r)=>s+r.average,0)/results.length):0; $('homeTrainings').textContent=results.length; $('homeAvg').textContent=avg+'%'; $('homeCases').textContent=activeCases().length; $('xpText').textContent=`${xp} XP acumulado`; $('xpBar').style.width=Math.min(100,xp%100)+'%'; $('levelLabel').textContent='Nível '+(Math.floor(xp/100)+1); }
function refreshNotifications(){ const ns=load(KEYS.notifications); const unread=ns.filter(n=>!n.read).length; $('notificationCount').textContent=unread; $('homeNotifications').textContent=ns.length; $('notificationList').innerHTML=ns.slice(0,5).map(n=>`<div class="notice"><b>${n.title}</b><p>${n.message}</p><small>${new Date(n.at).toLocaleString('pt-BR')}</small></div>`).join('') || '<p>Nenhuma notificação.</p>'; }
function refreshLibrary(){ const q=($('librarySearch').value||'').toLowerCase(), prod=$('libraryProduct').value; const items=getCases().filter(c=>(prod==='todos'||c.product===prod) && JSON.stringify(c).toLowerCase().includes(q)); $('libraryList').innerHTML=items.map(c=>caseCard(c)).join('') || '<p>Nenhum caso encontrado.</p>'; }
function refreshCasePanel(){ const q=($('casePanelSearch').value||'').toLowerCase(), prod=$('casePanelProduct').value; const items=getCases().filter(c=>(prod==='todos'||c.product===prod) && JSON.stringify(c).toLowerCase().includes(q)); $('casePanelList').innerHTML=items.map(c=>caseCard(c,true)).join('') || '<p>Nenhum caso cadastrado.</p>'; bindCasePanelActions(); }
function refreshManager(){ const results=load(KEYS.results), cases=getCases(); const avg=results.length?Math.round(results.reduce((s,r)=>s+r.average,0)/results.length):0; const solved=results.reduce((s,r)=>s+(r.solved||0),0); $('managerCards').innerHTML=`<div><span>Treinamentos</span><b>${results.length}</b></div><div><span>Média geral</span><b>${avg}%</b></div><div><span>Casos ativos</span><b>${activeCases().length}</b></div><div><span>Atendimentos</span><b>${solved}</b></div>`;
 const bySeller={}; results.forEach(r=>{bySeller[r.name]=bySeller[r.name]||{count:0,avg:0,xp:0}; bySeller[r.name].count++; bySeller[r.name].avg+=r.average; bySeller[r.name].xp+=r.xp;}); $('rankingList').innerHTML=Object.entries(bySeller).sort((a,b)=>b[1].xp-a[1].xp).map(([n,v],i)=>`<div class="caseCard"><b>${i+1}º ${n}</b><small>${v.count} treinos • média ${Math.round(v.avg/v.count)}% • ${v.xp} XP</small></div>`).join('')||'<p>Sem resultados.</p>';
 $('resultsList').innerHTML=results.slice(0,10).map(r=>`<div class="caseCard"><b>${r.name}</b><small>${r.mode} • ${r.average}% • ${new Date(r.at).toLocaleString('pt-BR')}</small><p>${r.solved} caso(s) resolvido(s)</p></div>`).join('')||'<p>Sem treinos.</p>';
 const stats={}; results.flatMap(r=>r.cases||[]).forEach(c=>{stats[c.caseId]=stats[c.caseId]||{uses:0,total:0,time:0,errors:0}; stats[c.caseId].uses++; stats[c.caseId].total+=c.score; stats[c.caseId].time+=c.time||0; if(c.score<70)stats[c.caseId].errors++;}); $('caseStatsList').innerHTML=cases.map(c=>{const s=stats[c.id]||{uses:0,total:0,time:0,errors:0}; return `<div class="caseCard"><b>${c.title}</b><small>${c.product} • ${c.difficulty}</small><div class="finalGrid"><div><span>Usos</span><b>${s.uses}</b></div><div><span>Nota média</span><b>${s.uses?Math.round(s.total/s.uses):0}%</b></div><div><span>Erros</span><b>${s.errors}</b></div><div><span>Tempo médio</span><b>${s.uses?Math.round(s.time/s.uses):0}s</b></div></div></div>`;}).join('');
 $('auditList').innerHTML=load(KEYS.audits).map(a=>`<div class="caseCard"><b>${a.action}: ${a.title}</b><small>${a.by} • ${new Date(a.at).toLocaleString('pt-BR')}</small></div>`).join('')||'<p>Sem alterações.</p>'; $('managerNoticeList').innerHTML=load(KEYS.notifications).map(n=>`<div class="notice"><b>${n.title}</b><p>${n.message}</p><small>${new Date(n.at).toLocaleString('pt-BR')}</small></div>`).join('')||'<p>Sem notificações.</p>'; }
function refreshAll(){ refreshHome(); refreshNotifications(); refreshLibrary(); refreshCasePanel(); refreshManager(); }
function startSession(){ const pool=filteredCases(selectedMode); if(!pool.length){ alert('Não há casos ativos para esse filtro.'); return;} currentSession={id:uid('sess'), mode:selectedMode, start:Date.now(), xp:0, solved:0, scores:[], cases:[]}; $('modeBadge').textContent=selectedMode==='plantao'?'Plantão':selectedMode==='conversa'?'Conversa IA':'Treinamento'; $('gameTitle').textContent=$('modeBadge').textContent; show('gameScreen'); renderQueue(); if(selectedMode==='plantao') startTimer(Number($('shiftTime').value)); else {$('timerLabel').textContent='Livre'; clearInterval(timer);} updateHud(); }
function startTimer(sec){ clearInterval(timer); let left=sec; timer=setInterval(()=>{left--; $('timerLabel').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`; if(left<=0) finishSession();},1000); }
function renderQueue(){ const pool=filteredCases(selectedMode); let list=selectedMode==='plantao'?shuffle(pool).slice(0,6):pool; $('caseQueue').innerHTML=list.map(c=>caseCard(c)).join(''); $$('#caseQueue .caseCard').forEach(el=>el.onclick=()=>selectCase(el.dataset.id)); }
function shuffle(a){ return [...a].sort(()=>Math.random()-.5); }
function selectCase(id){ activeCase=getCases().find(c=>c.id===id); conversationTurns=0; $('emptyService').classList.add('hidden'); $('activeService').classList.remove('hidden'); $('clientName').textContent=clientName(activeCase); $('clientAvatar').textContent=clientName(activeCase)[0]; $('clientMeta').textContent=`${activeCase.product} • ${activeCase.category} • ${activeCase.profile}`; $('historyList').innerHTML=(activeCase.history||[]).map(h=>`<div class="historyLine">${h}</div>`).join('')||'<p>Sem histórico.</p>'; $('chatBox').innerHTML=`<div class="msg clientMsg">${activeCase.message}</div>`; $('answerBox').value=''; $('supervisorBox').classList.add('hidden'); $$('#caseQueue .caseCard').forEach(e=>e.classList.toggle('active',e.dataset.id===id)); }
function clientName(c){ const names={Educado:'Carlos',Indeciso:'João',Bravo:'Marcos',Desconfiado:'Ana',Apressado:'Bruna','Muito Questionador':'Roberto',Comunicativo:'Mariana','Responde pouco':'Paulo'}; return names[c.profile]||'Cliente'; }
function evaluate(answer,c){ const txt=answer.toLowerCase(); const len=answer.trim().length; const risk=['garanto','garantido','100%','paga taxa','taxa para liberar','com certeza aprova','vai cair hoje','dash','sistema interno']; const ideal=(c.ideal||'').toLowerCase().split(/\W+/).filter(w=>w.length>4); const hits=ideal.filter(w=>txt.includes(w)).length; let empathy=/(entendo|compreendo|sinto muito|sem problemas|vou te ajudar|preocupação)/.test(txt)?88:55; let clarity=len>120?82:len>55?68:35; let safety=risk.some(r=>txt.includes(r))?25:85; let commercial=/(verificar|simulação|opção|alternativa|seguir|proposta|consultar|posso)/.test(txt)?82:50; let diagnosis=/(qual|motivo|por que|confortável|print|cpf|dados|modelo|ano)/.test(txt)?80:55; let idealScore=Math.min(95,45+hits*7); const total=Math.round((empathy+clarity+safety+commercial+diagnosis+idealScore)/6); return {total, metrics:{Empatia:empathy,Clareza:clarity,Segurança:safety,Comercial:commercial,Diagnóstico:diagnosis,Aderência:idealScore}, feedback: total>=85?'Ótima condução. Você acolheu, explicou e manteve o próximo passo.': total>=70?'Boa resposta, mas ainda dá para investigar melhor a objeção e conduzir com mais firmeza.':'Resposta fraca para treinamento. Faltou acolher, explicar melhor e conduzir o cliente para o próximo passo.', improvements: safety<60?'Cuidado com promessas ou termos internos.':'Procure sempre fechar com uma pergunta ou próximo passo claro.'}; }
function sendAnswer(){ if(!activeCase)return; const answer=$('answerBox').value.trim(); if(answer.length<2){alert('Digite uma resposta.'); return;} $('chatBox').insertAdjacentHTML('beforeend',`<div class="msg agentMsg">${answer}</div>`); const ev=evaluate(answer,activeCase); if(selectedMode==='conversa' && conversationTurns<2){ conversationTurns++; const next=nextClientMessage(activeCase,ev.total,conversationTurns); $('chatBox').insertAdjacentHTML('beforeend',`<div class="msg clientMsg">${next}</div>`); $('answerBox').value=''; return; } completeCase(ev,answer); }
function nextClientMessage(c,score,turn){ if(score>80) return turn===1?'Entendi. E como ficaria para eu seguir agora?':'Certo, pode me explicar o próximo passo então.'; if(c.profile==='Bravo') return 'Mas eu já estou cansado de esperar. Preciso de uma solução clara.'; if(c.profile==='Desconfiado') return 'Ainda fico com receio. Como eu sei que posso confiar?'; if(c.category==='Objeção') return 'Mesmo assim acho que vou pensar mais um pouco.'; return 'Tá, mas não entendi totalmente. Pode explicar de outro jeito?'; }
function completeCase(ev,answer){ currentSession.solved++; currentSession.xp+=ev.total; currentSession.scores.push(ev.total); currentSession.cases.push({caseId:activeCase.id,title:activeCase.title,score:ev.total,answer,time:Math.round((Date.now()-currentSession.start)/1000)}); $('supervisorBox').innerHTML=`<h3>Supervisor IA • Nota ${ev.total}%</h3><p>${ev.feedback}</p><div class="scoreGrid">${Object.entries(ev.metrics).map(([k,v])=>`<div><span>${k}</span><b>${Math.round(v)}%</b></div>`).join('')}</div><h3>Resposta ideal</h3><p>${activeCase.ideal||'Sem resposta ideal cadastrada.'}</p><p><b>Ponto de melhoria:</b> ${ev.improvements}</p>`; $('supervisorBox').classList.remove('hidden'); updateHud(); }
function updateHud(){ if(!currentSession)return; const avg=currentSession.scores.length?Math.round(currentSession.scores.reduce((a,b)=>a+b,0)/currentSession.scores.length):0; $('xpLabel').textContent=currentSession.xp; $('avgLabel').textContent=avg+'%'; $('solvedLabel').textContent=currentSession.solved; }
function finishSession(){ if(!currentSession)return; clearInterval(timer); const avg=currentSession.scores.length?Math.round(currentSession.scores.reduce((a,b)=>a+b,0)/currentSession.scores.length):0; const result={id:currentSession.id,name:$('sellerName').value||'Sem nome',team:$('sellerTeam').value,mode:$('modeBadge').textContent,average:avg,xp:currentSession.xp,solved:currentSession.solved,cases:currentSession.cases,at:new Date().toISOString()}; const results=load(KEYS.results); results.unshift(result); save(KEYS.results,results); localStorage.setItem(KEYS.xp,Number(localStorage.getItem(KEYS.xp)||0)+currentSession.xp); notify('Treinamento finalizado',`${result.name} finalizou ${result.mode} com média ${avg}%.`); currentSession=null; alert(`Sessão finalizada! Média: ${avg}%`); show('homeScreen'); refreshAll(); }
function fillForm(c){ $('caseId').value=c.id; $('caseTitle').value=c.title; $('caseProduct').value=c.product; $('caseCategory').value=c.category; $('caseDifficulty').value=c.difficulty; $('caseProfile').value=c.profile; $('caseStatus').value=c.status||'ativo'; $('caseTags').value=(c.tags||[]).join(', '); $('caseMessage').value=c.message||''; $('caseHistory').value=(c.history||[]).join('\n'); $('caseGoal').value=c.goal||''; $('caseIdeal').value=c.ideal||''; $('caseCriteria').value=c.criteria||''; $('caseHint').value=c.hint||''; $$('.modeCheck').forEach(ch=>ch.checked=(c.modes||[]).includes(ch.value)); window.scrollTo(0,0); }
function clearForm(){ $('caseForm').reset(); $('caseId').value=''; $$('.modeCheck').forEach(ch=>ch.checked=true); }
function bindCasePanelActions(){ $$('.editCase').forEach(b=>b.onclick=e=>{e.stopPropagation(); fillForm(getCases().find(c=>c.id===b.dataset.id));}); $$('.dupCase').forEach(b=>b.onclick=e=>{e.stopPropagation(); const c={...getCases().find(x=>x.id===b.dataset.id)}; c.id=uid('caso'); c.title+=' (cópia)'; const cases=getCases(); cases.unshift(c); setCases(cases); audit('Duplicou',c.title); notify('Caso duplicado',c.title);}); $$('.toggleCase').forEach(b=>b.onclick=e=>{e.stopPropagation(); const cases=getCases(); const c=cases.find(x=>x.id===b.dataset.id); c.status=c.status==='inativo'?'ativo':'inativo'; setCases(cases); audit(c.status==='ativo'?'Ativou':'Inativou',c.title);}); $$('.delCase').forEach(b=>b.onclick=e=>{e.stopPropagation(); if(!confirm('Excluir este caso?'))return; const cases=getCases(); const c=cases.find(x=>x.id===b.dataset.id); setCases(cases.filter(x=>x.id!==b.dataset.id)); audit('Excluiu',c?.title||b.dataset.id);}); }
function submitCase(e){ e.preventDefault(); const id=$('caseId').value||uid('caso'); const c={id,title:$('caseTitle').value,product:$('caseProduct').value,category:$('caseCategory').value,difficulty:$('caseDifficulty').value,profile:$('caseProfile').value,status:$('caseStatus').value,modes:$$('.modeCheck').filter(ch=>ch.checked).map(ch=>ch.value),tags:$('caseTags').value.split(',').map(x=>x.trim()).filter(Boolean),message:$('caseMessage').value,history:$('caseHistory').value.split('\n').map(x=>x.trim()).filter(Boolean),goal:$('caseGoal').value,ideal:$('caseIdeal').value,criteria:$('caseCriteria').value,hint:$('caseHint').value}; const cases=getCases(); const idx=cases.findIndex(x=>x.id===id); if(idx>=0){cases[idx]=c; audit('Editou',c.title);} else {cases.unshift(c); audit('Criou',c.title); notify('Novo caso cadastrado',c.title);} setCases(cases); clearForm(); }
function toCsv(rows){ if(!rows.length)return ''; const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))]; return [keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(Array.isArray(r[k])?r[k].join('|'):r[k]??'').replace(/"/g,'""')}"`).join(';'))].join('\n'); }
function download(name,content,type='text/plain'){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
function parseCsv(text){ const lines=text.split(/\r?\n/).filter(Boolean); const headers=lines.shift().split(';').map(h=>h.replace(/^"|"$/g,'')); return lines.map(line=>{const vals=line.match(/("[^"]*(?:""[^"]*)*"|[^;]+)/g)||[]; const obj={}; headers.forEach((h,i)=>obj[h]=String(vals[i]||'').replace(/^"|"$/g,'').replace(/""/g,'"')); obj.id=obj.id||uid('caso'); obj.tags=String(obj.tags||'').split('|').filter(Boolean); obj.modes=String(obj.modes||'plantao|treinamento').split('|').filter(Boolean); obj.history=String(obj.history||'').split('|').filter(Boolean); return obj;}); }
function importCases(file){ const reader=new FileReader(); reader.onload=()=>{const txt=reader.result; let imported=[]; if(file.name.endsWith('.json')) imported=JSON.parse(txt); else imported=parseCsv(txt); const cases=[...imported,...getCases()]; setCases(cases); audit('Importou',`${imported.length} casos`); notify('Importação de casos',`${imported.length} casos foram importados.`);}; reader.readAsText(file); }
function initEvents(){ $('goHome').onclick=()=>show('homeScreen'); $('openLibraryBtn').onclick=()=>{refreshLibrary();show('libraryScreen')}; $('closeLibrary').onclick=()=>show('homeScreen'); $('openCasesPanel').onclick=()=>show('casePanelScreen'); $('openManagerPanel').onclick=()=>show('managerScreen'); $$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('activeMode')); b.classList.add('activeMode'); selectedMode=b.dataset.mode;}); $('startBtn').onclick=startSession; $('newRandomCase').onclick=renderQueue; $('sendAnswerBtn').onclick=sendAnswer; $('hintBtn').onclick=()=>activeCase&&alert(activeCase.hint||'Sem dica cadastrada.'); $('finishBtn').onclick=finishSession; $('caseLoginBtn').onclick=()=>{ if($('casePassword').value===CASE_PASS){$('caseLogin').classList.add('hidden');$('casePanel').classList.remove('hidden');refreshCasePanel();}else alert('Senha incorreta.');}; $('managerLoginBtn').onclick=()=>{ if($('managerPassword').value===MANAGER_PASS){$('managerLogin').classList.add('hidden');$('managerPanel').classList.remove('hidden');refreshManager();}else alert('Senha incorreta.');}; $('caseLogoutBtn').onclick=()=>{$('casePanel').classList.add('hidden');$('caseLogin').classList.remove('hidden');}; $('managerLogoutBtn').onclick=()=>{$('managerPanel').classList.add('hidden');$('managerLogin').classList.remove('hidden');}; $('caseForm').onsubmit=submitCase; $('clearCaseForm').onclick=clearForm; ['librarySearch','libraryProduct'].forEach(id=>$(id).oninput=refreshLibrary); ['casePanelSearch','casePanelProduct'].forEach(id=>$(id).oninput=refreshCasePanel); $('exportCasesJsonBtn').onclick=()=>download('casos_concredito.json',JSON.stringify(getCases(),null,2),'application/json'); $('exportCasesCsvBtn').onclick=()=>download('casos_concredito.csv',toCsv(getCases()),'text/csv'); $('importCasesBtn').onclick=()=>$('caseFileInput').click(); $('caseFileInput').onchange=e=>e.target.files[0]&&importCases(e.target.files[0]); $('exportResultsCsvBtn').onclick=()=>download('resultados_concredito.csv',toCsv(load(KEYS.results)),'text/csv'); $('noticeForm').onsubmit=e=>{e.preventDefault(); notify($('noticeTitle').value,$('noticeMessage').value); $('noticeForm').reset(); refreshManager();}; $$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('activeTab')); t.classList.add('activeTab'); $$('.tabPanel').forEach(p=>p.classList.add('hidden')); $('manager'+t.dataset.tab[0].toUpperCase()+t.dataset.tab.slice(1)).classList.remove('hidden');}); $('notificationBtn').onclick=()=>{const ns=load(KEYS.notifications).map(n=>({...n,read:true})); save(KEYS.notifications,ns); refreshNotifications(); alert('Notificações marcadas como lidas.');}; }
fillSelects(); clearForm(); initEvents(); refreshAll();
